### ISSUE TITLE
想对各位考研学子说的话

### ISSUE THREAD

**Issue by LiYukeee** [fjh1997/RuanWeiBible#11]
如果你是一战，我建议你去考软微，拿下top2人这一辈子就满足了
如果你是二战，我建议你去考软微，有过一战的沉淀二战的你已经无比强大，数据也显示软微二战上岸率很高
如果你是三战，我建议你考软微，因为软微放两年实习，考上了之前两战浪费的时间通通弥补
如果你是四战，我还是建议你考软微，此时的你已经无牵无挂，工作丢了，女朋友跑了，父母失望了，朋友失联了，唯有上北大你才能拿回属于你的一切

**Comment by Zhenhao-Zhang** [comment]
rw！rw！rw！

**Comment by syficy** [comment]
已合入
