### ISSUE TITLE
保研福音

### ISSUE THREAD

**Issue by BenChenEternity** [fjh1997/RuanWeiBible#12]
第一节
保研？在我的字典里只有“考研”和“软微”四个字。在放弃保研承诺书上签下自己姓名的那一刻起，我就知道我是注定迎来那场深埋大雪的天选之人。保！随你们怎么保罢！

第二节
为了那所谓的安全稳定，甘愿在舒适区，难道心中真的没有对更高理想的渴望？一味地沉迷于科研，追求顶刊上有自己的名字，仿佛以为自己是在为未来铺路，其实不过在自我麻痹！你们没有经历过11408洗礼，没有面对窒息的压迫感，为了本校研究生的光环，争先恐后，似乎这就是你们的终极目标，亦可笑矣！本校的导师随便你们怎么挑，和我一点关系都没有，燕雀安知鸿鹄之志，我已经在图书馆恭迎那场大雪的到来；待你们为本校老板所奴役之时，我已于大兴呼吸着属于软微人自由的气息。

**Comment by syficy** [comment]
已合入

**Comment by BenChenEternity** [comment]
噫！好了！我中了！
9月开学去咯
