### ISSUE TITLE
一个北憨的十年

### ISSUE THREAD

**Issue by qingoba** [fjh1997/RuanWeiBible#8]
一个北憨的十年：
17岁：表白同桌女神，女神让你好好照照镜子
18岁：高考失利，上了当地不知名二本学土木，被亲戚冷嘲热讽。
19岁：上大学每天逃课，挂了三科，游戏打到了黄金段位。
20岁：喜欢上社团一个妹子，某天晚上却看着她上了富二代同学的车。
21岁：同学聚会，听着高中同学们分享各自在985211的精彩大学生活，满怀羡慕。
22岁：考研北大软微，发现点击就送，388低分上岸。学校把你当优秀毕业生挂红榜宣传，亲戚们看到你大红色录取通知书眼神开始变得有些不一样。
23岁：再次同学聚会，看着曾经高中学了985生化环材的同学处境，心里满怀庆幸
24岁：刷了两个月leetcode去实习，一个月轻松破万，高中时女神看了你朋友圈后开始联系你，你有点爱理不理。
25岁：边实习边完成毕业论文，看着新闻上研究生导师压榨重开，心中满是感慨。
26岁：毕业后进入一家互联网大厂，轻松拿到了sp，总包50W，并走单列计划拿到了北京户口。
27岁：年薪涨到了60W，亲戚们开始给你介绍对象，但是你都看不上。最终你选择了一个北京有房的姑娘相处，饭桌上她爸爸夸你年轻有为。
选择远大于努力，选择软微，选择成功。

**Comment by syficy** [comment]
已合入
