### ISSUE TITLE
卖火柴的北憨

### ISSUE THREAD

**Issue by hhzzll** [fjh1997/RuanWeiBible#9]
北憨点燃了第一根火柴，他看见自己考研初试成绩查询420分。
北憨点燃了第二根火柴，他看见自己拿着大红色的北京大学录取通知书，父母投来赞许的目光，亲戚朋友纷纷祝贺。
北憨点燃了第三根火柴，他看见自己坐上了上面写有“北京大学软件与微电子学院”的校车，飞速开往大兴，车上每个人都洋溢着幸福的笑脸。
北憨点燃了第四根火柴，看到在未名湖畔自己拿着一本程序与算法设计，看得那么入迷，旁边就是博雅塔，有小姐姐在石舫上拍照。
北憨害怕火柴灭了，研究生、北大、大学深埋、未名湖畔，博雅塔前的生活会一样样消失不见，就点燃了所有的火柴，想要把这些美好留在身边.....火柴灭了，四周一片漆黑，北憨幸福地闭上了眼睛。
第二天，人们看到一个北憨背着重重的书包，装着厚厚的王道408朝图书馆走着，他脸上放着光彩，嘴边露着微笑，手中还拿着一个空的火柴盒。

**Comment by syficy** [comment]
已合入
